# Example 02: Full TLS Configuration with Security Headers
# Demonstrates: force-ssl-redirect, ssl-ciphers, auth-tls-secret, custom HSTS headers
# Migration complexity: COMPLEX (auth-tls-secret requires special handling)
# Target:
#   Traefik: RedirectScheme middleware + ServersTransport for client certs
#   Gateway API: RequestRedirect filter + TLS on Gateway listener

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secure-banking-app
  namespace: fintech
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384"
    nginx.ingress.kubernetes.io/proxy-ssl-secret: "fintech/backend-client-cert"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "on"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/custom-headers: "fintech/security-headers"
    # HSTS via configuration snippet (NOTE: snippets are UNSUPPORTED in most alternatives)
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload";
      more_set_headers "Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'";
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - banking.example.com
        - api.banking.example.com
      secretName: banking-tls-secret
  rules:
    - host: banking.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: banking-frontend
                port:
                  number: 443
    - host: api.banking.example.com
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: banking-api
                port:
                  number: 8443
          - path: /v2
            pathType: Prefix
            backend:
              service:
                name: banking-api-v2
                port:
                  number: 8443

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: security-headers
  namespace: fintech
data:
  Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
  X-Frame-Options: "DENY"
  X-Content-Type-Options: "nosniff"
  X-XSS-Protection: "1; mode=block"
  Content-Security-Policy: "default-src 'self'"
  Referrer-Policy: "no-referrer"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-frontend
  namespace: fintech
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banking-frontend
  template:
    metadata:
      labels:
        app: banking-frontend
    spec:
      containers:
        - name: frontend
          image: nginx:1.25
          ports:
            - containerPort: 443

---
apiVersion: v1
kind: Service
metadata:
  name: banking-frontend
  namespace: fintech
spec:
  selector:
    app: banking-frontend
  ports:
    - port: 443
      targetPort: 443
