# Example 06: Full CORS Configuration
# Demonstrates: enable-cors, cors-allow-origin, cors-allow-methods, cors-allow-headers,
#               cors-expose-headers, cors-allow-credentials, cors-max-age
# Migration complexity: COMPLEX
# Target:
#   Traefik: Headers Middleware with CORS settings (fully supported)
#   Gateway API: ResponseHeaderModifier filter (manual CORS headers)

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-api
  namespace: platform
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://app.example.com,https://admin.example.com,https://mobile.example.com"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,X-API-Key,X-Correlation-ID"
    nginx.ingress.kubernetes.io/cors-expose-headers: "Content-Length,Content-Range,X-Request-ID,X-RateLimit-Remaining"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-max-age: "1728000"
    nginx.ingress.kubernetes.io/limit-rps: "100"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "2"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.platform.example.com
      secretName: platform-api-tls
  rules:
    - host: api.platform.example.com
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: api-v1
                port:
                  number: 8080
          - path: /v2
            pathType: Prefix
            backend:
              service:
                name: api-v2
                port:
                  number: 8080
          - path: /graphql
            pathType: Exact
            backend:
              service:
                name: graphql-api
                port:
                  number: 4000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-v2
  namespace: platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-v2
  template:
    metadata:
      labels:
        app: api-v2
    spec:
      containers:
        - name: api
          image: node:20-alpine
          ports:
            - containerPort: 8080
          command: ["node", "-e", "require('http').createServer((req,res)=>{res.writeHead(200);res.end('v2')}).listen(8080)"]

---
apiVersion: v1
kind: Service
metadata:
  name: api-v2
  namespace: platform
spec:
  selector:
    app: api-v2
  ports:
    - port: 8080
      targetPort: 8080
