# Example 07: Path Rewriting with Regex
# Demonstrates: rewrite-target with capture groups, use-regex, app-root
# Migration complexity: COMPLEX
# Target:
#   Traefik: ReplacePathRegex Middleware (supported, regex syntax slightly different)
#   Gateway API: URLRewrite filter with ReplaceFullPath (regex captures need manual conversion)

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-gateway
  namespace: services
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Strips the /service-name/ prefix before forwarding
    # e.g., /users/list → /list  (capture group removes prefix)
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    nginx.ingress.kubernetes.io/app-root: "/home"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "5"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - gateway.example.com
      secretName: gateway-tls
  rules:
    - host: gateway.example.com
      http:
        paths:
          # /users/anything → /anything on user-service
          - path: /users(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-service
                port:
                  number: 8080
          # /orders/anything → /anything on order-service
          - path: /orders(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: order-service
                port:
                  number: 8080
          # /products/anything → /anything on product-service
          - path: /products(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: product-service
                port:
                  number: 8080
          # /notifications/anything → /anything
          - path: /notifications(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: notification-service
                port:
                  number: 8080

---
# A second ingress showing version-based rewriting
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-version-router
  namespace: services
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Strip version prefix: /v[0-9]+/path → /path
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
spec:
  ingressClassName: nginx
  rules:
    - host: versioned-api.example.com
      http:
        paths:
          - path: /v[0-9]+(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-service
                port:
                  number: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: service
          image: nginx:1.25
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: services
spec:
  selector:
    app: user-service
  ports:
    - port: 8080
      targetPort: 8080
