# Example 08: Rate Limiting + IP Access Control
# Demonstrates: limit-rps, limit-connections, limit-burst-multiplier, limit-whitelist,
#               whitelist-source-range, denylist-source-range
# Migration complexity: COMPLEX
# Target:
#   Traefik: RateLimit + InFlightReq + IPAllowList + IPDenyList Middlewares
#   Gateway API: BackendTrafficPolicy (RateLimit) + SecurityPolicy (IPFilter) via Envoy Gateway

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rate-limited-api
  namespace: security
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # Rate limiting: max 10 requests/second per IP, burst up to 50
    nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "5"
    nginx.ingress.kubernetes.io/limit-connections: "20"
    # Exempt internal IPs from rate limiting
    nginx.ingress.kubernetes.io/limit-whitelist: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
    # Allow only specific external CIDRs
    nginx.ingress.kubernetes.io/whitelist-source-range: "203.0.113.0/24,198.51.100.0/24,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
    # Block known malicious ranges
    nginx.ingress.kubernetes.io/denylist-source-range: "192.0.2.0/24,198.19.0.0/16"
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "5"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - secure-api.example.com
      secretName: secure-api-tls
  rules:
    - host: secure-api.example.com
      http:
        paths:
          - path: /api/v1/data
            pathType: Prefix
            backend:
              service:
                name: data-api
                port:
                  number: 8080
          - path: /api/v1/upload
            pathType: Prefix
            backend:
              service:
                name: upload-api
                port:
                  number: 8080

---
# More aggressive rate limiting for payment endpoint
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment-api
  namespace: security
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/limit-rps: "2"
    nginx.ingress.kubernetes.io/limit-connections: "5"
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,203.0.113.10/32"
    nginx.ingress.kubernetes.io/auth-url: "https://auth.example.com/validate"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-User-ID,X-User-Role"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - payments.example.com
      secretName: payments-tls
  rules:
    - host: payments.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: payment-processor
                port:
                  number: 9090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-api
  namespace: security
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-api
  template:
    metadata:
      labels:
        app: data-api
    spec:
      containers:
        - name: api
          image: nginx:1.25
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: data-api
  namespace: security
spec:
  selector:
    app: data-api
  ports:
    - port: 8080
      targetPort: 8080
